name: Build Run

on:
  workflow_dispatch:
    inputs:
      url:
        description: 'サイトを選択してください'
        required: true
        type: choice
        options:
          - AIRDO
          - RECRUIT_AGENT

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Install Linux dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libnspr4 \
            libnss3 \
            libasound2t64

      - name: Set config
        env:
          AIRDO_SETTING: ${{ secrets.AIRDO_SETTING }}
          RECRUIT_AGENT_SETTING: ${{ secrets.RECRUIT_AGENT_SETTING }}
        run: |
          case "${{ inputs.url }}" in
            AIRDO)
              CONFIG="$AIRDO_SETTING"
              ;;
            RECRUIT_AGENT)
              CONFIG="$RECRUIT_AGENT_SETTING"
              ;;
          esac

          {
            echo "CONFIG_SETTING<<EOF"
            echo "$CONFIG"
            echo "EOF"
          } >> "$GITHUB_ENV"

      - name: Build with Gradle
        run: ./gradlew build

      - name: Create screenshots directory
        run: mkdir -p screenshots

      - name: Run jar
        run: |
          java -jar build/libs/*.jar
      
      - name: Upload Screenshot
        uses: actions/upload-artifact@v4
        with:
          name: screenshot
          path: after-login.png