name: Build Run

on:
  workflow_dispatch:
    inputs:
      site:
        description: 'サイトを選択してください'
        required: true
        type: choice
        options:
          - AIRDO
          - RECRUIT_AGENT

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Install Linux dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libnspr4 \
            libnss3 \
            libasound2t64

      - name: Set config
        env:
          AIRDO_LOGIN_ID: ${{ secrets.AIRDO_LOGIN_ID }}
          AIRDO_PASSWORD: ${{ secrets.AIRDO_PASSWORD }}
          RECRUIT_AGENT_LOGIN_ID: ${{ secrets.RECRUIT_AGENT_LOGIN_ID }}
          RECRUIT_AGENT_PASSWORD: ${{ secrets.RECRUIT_AGENT_PASSWORD }}
        run: |
          case "${{ inputs.site }}" in
            AIRDO)
              LOGIN_ID="$AIRDO_LOGIN_ID"
              PASSWORD="$AIRDO_PASSWORD"
              ;;
            RECRUIT_AGENT)
              LOGIN_ID="$RECRUIT_AGENT_LOGIN_ID"
              PASSWORD="$RECRUIT_AGENT_PASSWORD"
              ;;
          esac

          echo "LOGIN_ID=$LOGIN_ID" >> $GITHUB_ENV
          echo "PASSWORD=$PASSWORD" >> $GITHUB_ENV

      - name: Build with Gradle
        run: ./gradlew build

      - name: Create screenshots directory
        run: mkdir -p screenshots

      - name: Install Japanese Fonts
        run: |
          sudo apt-get update
          sudo apt-get install -y fonts-noto-cjk
          fc-cache -fv

      - name: Run jar
        run: |
          java -jar build/libs/*.jar \
            "${{ github.event.inputs.site }}"
      
      - name: Upload Screenshot
        uses: actions/upload-artifact@v4
        with:
          name: screenshot
          path: after-login.png